<?php echo $this->doctype() ?>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="chrome=1">
	<meta http-equiv="Content-Type" content="text/html" charset="utf-8">

	<title>Prueba Alegra Clientes</title>
	<link type="image/x-icon" rel="shortcut icon" href="https://cdn1.alegra.com/images/favicon.ico">
	<?php
		echo $this->headLink()
			->appendStylesheet('/ext4/resources/css/ext-all-neptune.css')
			->appendStylesheet('/resources/css/app.css');
	?>
	<!-- Ext JS -->
	<?php
		echo $this->headScript()
			->appendFile('ext4/ext-all-debug.js')
			->appendFile('app.js');
	?>
	<script type="text/javascript" src="https://cdn1.alegra.com/long-term/compressed/ext-lang-es.js"></script>
</head>
<body>
	<?php  echo $this->layout()->content ?>
</body>
</html>
